# Generated by Django 5.1.5 on 2025-08-02 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('properties', '0003_remove_property_property_type_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to='properties.property'),
        ),
    ]
