# Generated by Django 5.1.5 on 2025-08-03 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_propertyview_property'),
        ('listings', '0001_initial'),
        ('properties', '0007_remove_property_air_conditioning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_property_like',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_listing_like',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_property_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_listing_favorite',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'property'), name='unique_property_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='unique_listing_favorite'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'property'), name='unique_property_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='unique_listing_like'),
        ),
    ]
