# Generated by Django 5.1.5 on 2025-08-01 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_currency_alter_country_currency'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='locations.currency'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
