# Generated by Django 5.1.5 on 2025-08-02 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_currency_delete_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='listing_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='views_count',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_footage',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='order_sequence',
        ),
        migrations.AddField(
            model_name='property',
            name='buildable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('land', 'Land')], default='real_estate', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_type',
            field=models.CharField(blank=True, choices=[('residential_land', 'Residential Land'), ('commercial_land', 'Commercial Land'), ('agricultural_land', 'Agricultural Land'), ('industrial_land', 'Industrial Land'), ('mixed_use_land', 'Mixed Use Land'), ('development_land', 'Development Land')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease'), ('auction', 'Auction')], default='sales', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='premium_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='real_estate_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('loft', 'Loft'), ('penthouse', 'Penthouse'), ('commercial', 'Commercial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='topography',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='utilities_available',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold'), ('rented', 'Rented'), ('off_market', 'Off Market')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('agency', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='agents/')),
                ('specializations', models.JSONField(default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sales', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property')),
            ],
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
    ]
