# Generated by Django 5.1.5 on 2025-08-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_userprofile_rating_userprofile_specializations_and_more'),
        ('properties', '0003_remove_property_property_type_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_properties', to='Auth.userprofile'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
