# Generated by Django 5.1.5 on 2025-08-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_rename_code_currency_name_and_more'),
        ('properties', '0004_alter_property_agent_delete_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('land', 'Land')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.currency'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease'), ('auction', 'Auction')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold'), ('rented', 'Rented'), ('off_market', 'Off Market')], max_length=15, null=True),
        ),
    ]
