# Generated by Django 5.1.5 on 2025-08-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_air_conditioning_property_balcony_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='air_conditioning',
        ),
        migrations.RemoveField(
            model_name='property',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='property',
            name='dishwasher',
        ),
        migrations.RemoveField(
            model_name='property',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='property',
            name='fireplace',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='property',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='property',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='property',
            name='laundry',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='property',
            name='security_system',
        ),
    ]
