# Generated by Django 5.1.5 on 2025-08-01 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('CFA_Francs', 'XAF'), ('US_Dollars', 'USD'), ('Nigerian_Naira', 'Naira'), ('French_Euros', 'Euros')], max_length=15, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(default=0, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.currency'),
        ),
    ]
