# Generated by Django 5.1.5 on 2025-08-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_currency_alter_country_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
    ]
