# Generated by Django 5.1.5 on 2025-08-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('XAF', 'XAF'), ('USD', 'USD'), ('Naira', 'Naira'), ('Euros', 'Euros')], max_length=15, unique=True),
        ),
    ]
