# Generated by Django 5.1.5 on 2025-08-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_currency_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='code',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
